# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bbe0f9e595de3b66839e1d2e7f6ecfd97809bc64a708d62775ef4ab385f7d3705b8112581d6df779eb3f14749bd8500bc0d44913c2aa9671dbb01519add170e6

test:
  secret_key_base: 2d1da6763d7287bcba1928df8383ee61040d4d67e92ae7f2180db73739acec0399547e2565597c1bb5f8445424c757369c0d7a3127b6c25b8b274bbc5ca5290d

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
